leftnav:
- identifier: 49661194-45b0-09ff-1d83-52cac229a069
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: a620dfea-71bd-b32b-42f9-255bb34566eb
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 45990c92-6ed7-154d-0b43-edbe63e00311
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 85b33ea9-7271-323b-e674-6ae4183b0435
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: af092b8f-557e-5f39-0bb3-165b3acb3367
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
